### PR TITLE
Codespiderr

### PR DESCRIPTION
**Pull request by codespiderr**
I added music to the game using the pygame library

### CODE REVIEW

**Comment by sxijyoti** [comment]
there is error with the importing of the song 
image

**Comment by codespiderr** [comment]
I fixed the path of the file please try once now

**Comment by sxijyoti** [comment]
that is cool but you haven't implemented it any of the screens. will give you 15 points for trying

**Comment by sxijyoti** [comment]
!bounty 15

**Comment by sxijyoti** [comment]
!bounty 5

**Pull request closed without merging**
